### ISSUE TITLE
Global Poorest

### ISSUE THREAD

**Issue by bill-anderson** [devinit/digital-platform#27]
Concept = 
Check data
Check metadata

**Comment by akmiller01** [comment]
Missing piece of data:

Percent of the population that falls under the global poorest 20%. I believe this translates to the % of the population under $1.48 per day, but that will be a changing measure.

**Comment by akmiller01** [comment]
Quick note: Since the global definition of poorest 20% is constantly changing, a methodologically sound (although computationally and space inefficient) method of representing this data could be as such:

| id | year | level | percent |
|----|------|-------|---------|
| AF | 2000 | 1.48 | 25.5 |
| AF | 2000 | 1.49 | 27.3 |
| AF | 2000 | 1.50 | 30.9 |

If we could arrange the data like that, we wouldn't have to generate a new dataset every time the global definition changed. It might not be possible given our resources, however, so for now we may need to just pick $1.48 as the level (if that is what it is presently) and represent the data like this:

| id | year | value |
|----|------|-------|
| AF | 2000 | 25.5 |
| AF | 2001 | 23.7 |
| AF | 2002 | 22.1 |

**Comment by timstrawson** [comment]
I've added a file with the number of people in each country that are part of the global poorest 20%, based on the 2011 povcal model (so currently only shows data for 2011). Data are draft - Dan W to finalise once he is back (he's unwell today).

**Comment by akmiller01** [comment]
@timstrawson quick question: Why is this data extended out to 2 decimal places in some countries? E.g.

| id | year | value |
|----|------|------------|
| BR | 2011 | 188,852.03 |

**Comment by bill-anderson** [comment]
Also @timstrawson commas are in the data, which make the values non-numeric

**Comment by timstrawson** [comment]
Thanks both, the decimals are an artefact of the calculation. Probably sensible to round to the nearest whole person! I'll fix now

**Comment by timstrawson** [comment]
I've now added a second file giving the proportion of the population of each country that is part of the global poorest 20% as I think we want to give the option to toggle between these two measures in the country profiles
